# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: bilalamjaddev/three-tier-frontend:latest  # Replace with your Docker Hub username
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://43.204.32.0:30001/api/tasks"  # Replace with your EC2 public IP
        ports:
        - containerPort: 3000
